import { execSync } from 'node:child_process';
import { existsSync, readdirSync, statSync, mkdirSync, writeFileSync, readFileSync, appendFileSync } from 'node:fs';
import { join } from 'node:path';
import { createInterface } from 'node:readline';

function findGitRoot(dir) {
  let d = dir;
  while (d !== join(d, '..')) {
    if (existsSync(join(d, '.git'))) return d;
    d = join(d, '..');
  }
  return null;
}

/** Find all git repos under a directory (non-recursive into nested git repos) */
function findGitRepos(root, maxDepth = 4, depth = 0) {
  if (depth > maxDepth) return [];
  const repos = [];
  try {
    for (const entry of readdirSync(root)) {
      if (entry.startsWith('.')) continue;
      const full = join(root, entry);
      try {
        if (!statSync(full).isDirectory()) continue;
        if (existsSync(join(full, '.git'))) {
          repos.push(full); // don't recurse into nested git repos
        } else {
          repos.push(...findGitRepos(full, maxDepth, depth + 1));
        }
      } catch { /* skip permission errors */ }
    }
  } catch {}
  return repos;
}

async function prompt(rl, question) {
  return new Promise(r => rl.question(question, r));
}

async function confirm(rl, question, defaultYes = true) {
  const hint = defaultYes ? '[Y/n]' : '[y/N]';
  const ans = (await prompt(rl, `${question} ${hint} `)).trim().toLowerCase();
  return ans === '' ? defaultYes : ans === 'y' || ans === 'yes';
}

/** Create .myelin/ project dir, gitignore it, write project.yml */
function initMyelinDir(root, tools) {
  const dir = join(root, '.myelin');
  mkdirSync(dir, { recursive: true });

  // Write project.yml (track init state)
  const yml = `# Myelin project configuration
# Generated by: myelin init
project: ${root.split(/[\\/]/).pop()}
initialized: ${new Date().toISOString()}
tools:
${tools.map(t => `  ${t}: true`).join('\n')}
`;
  writeFileSync(join(dir, 'project.yml'), yml, 'utf8');

  // Gitignore .myelin/ (default: not committed — personal state)
  const gitignore = join(root, '.gitignore');
  const marker = '.myelin/';
  if (existsSync(gitignore)) {
    const content = readFileSync(gitignore, 'utf8');
    if (!content.includes(marker)) appendFileSync(gitignore, `\n# Myelin project state\n${marker}\n`);
  } else {
    writeFileSync(gitignore, `# Myelin project state\n${marker}\n`);
  }
}

const TOOLS = [
  {
    id: 'serena',
    label: 'Serena (LSP code index — symbol-precise navigation)',
    check: (root) => existsSync(join(root, '.serena', 'project.yml')) || existsSync(join(root, '.myelin', 'project.yml')),
    run:   (root) => execSync(`serena project create --index "${root}"`, { stdio: 'inherit' }),
  },
  {
    id: 'semble',
    label: 'Semble (semantic code search index)',
    check: (_root) => false,
    run:   (root) => execSync(`semble --content code`, { cwd: root, stdio: 'inherit' }),
  },
];

async function initRepo(root, yes, rl, enabledTools) {
  const name = root.split(/[\\/]/).pop();
  console.log(`\n   📁 ${name}  (${root})`);
  const results = [];
  for (const tool of TOOLS.filter(t => enabledTools.includes(t.id))) {
    const alreadyDone = tool.check(root);
    const labelSuffix = alreadyDone ? ' (already done — re-run?)' : '';
    let run = yes;
    if (!yes) run = await confirm(rl, `      Run ${tool.id}${labelSuffix}?`, !alreadyDone);
    if (run) {
      try { tool.run(root); console.log(`      ✓ ${tool.id}`); results.push({ ok: true }); }
      catch (e) { console.warn(`      ⚠ ${tool.id} failed: ${e.message.split('\n')[0]}`); results.push({ ok: false }); }
    } else {
      console.log(`      · ${tool.id} skipped`);
    }
  }
  initMyelinDir(root, results.filter(r => r.ok).map((_, i) => enabledTools[i]));
  return results;
}

export async function runInit({ yes = false, recursive = false, dir = process.cwd(), depth = 4 } = {}) {
  let rl;

  // Collect repos to init
  let repos = [];
  if (recursive) {
    repos = findGitRepos(dir, depth);
    if (repos.length === 0) {
      console.log(`\n⚠  No git repositories found under ${dir}\n`); return false;
    }
    console.log(`\n🧬 Myelin Init (recursive) — found ${repos.length} repo(s) under ${dir}`);
    repos.forEach((r, i) => console.log(`   ${i + 1}. ${r.replace(dir, '.')}`));
  } else {
    const root = findGitRoot(dir);
    if (!root) { console.log(`\n⚠  Not inside a git repository (cwd: ${dir})\n`); return false; }
    repos = [root];
    console.log(`\n🧬 Myelin Init — ${root.split(/[\\/]/).pop()}  (${root})`);
  }

  if (!yes) {
    rl = createInterface({ input: process.stdin, output: process.stdout });
    const proceed = await confirm(rl, `\n   Initialize ${repos.length} repo(s)?`);
    if (!proceed) { rl.close(); console.log('   Cancelled.\n'); return false; }
  }

  // Choose tools (once, applies to all repos)
  let enabledTools = TOOLS.map(t => t.id);
  if (!yes && rl) {
    console.log('\n   Select tools to run:');
    enabledTools = [];
    for (const tool of TOOLS) {
      const run = await confirm(rl, `     ${tool.label}?`);
      if (run) enabledTools.push(tool.id);
    }
  }

  let total = 0, ok = 0;
  for (const root of repos) {
    const results = await initRepo(root, yes, rl, enabledTools);
    total += results.length;
    ok += results.filter(r => r.ok).length;
  }

  if (rl) rl.close();
  console.log(`\n   ✓ Init complete — ${ok}/${total} operations succeeded across ${repos.length} repo(s).\n`);
  return true;
}
