import { execSync, spawn } from 'node:child_process';
import { existsSync, readdirSync, statSync, mkdirSync, writeFileSync, readFileSync, appendFileSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';
import { createInterface } from 'node:readline';
import { load as parseYaml } from 'js-yaml';
import { DEFAULT_CONFIG, mergeDeep } from '../config/schema.mjs';
import { renderManagedBlock } from '../config/instruction-snippets.mjs';
import { writeManagedSection } from '../config/managed-section.mjs';

function findGitRoot(dir) {
  let d = dir;
  while (d !== join(d, '..')) {
    if (existsSync(join(d, '.git'))) return d;
    d = join(d, '..');
  }
  return null;
}

/** Find all git repos under a directory (non-recursive into nested git repos) */
function findGitRepos(root, maxDepth = 4, depth = 0) {
  if (depth > maxDepth) return [];
  const repos = [];
  try {
    for (const entry of readdirSync(root)) {
      if (entry.startsWith('.')) continue;
      const full = join(root, entry);
      try {
        if (!statSync(full).isDirectory()) continue;
        if (existsSync(join(full, '.git'))) {
          repos.push(full); // don't recurse into nested git repos
        } else {
          repos.push(...findGitRepos(full, maxDepth, depth + 1));
        }
      } catch { /* skip permission errors */ }
    }
  } catch {}
  return repos;
}

async function prompt(rl, question) {
  return new Promise(r => rl.question(question, r));
}

async function confirm(rl, question, defaultYes = true) {
  const hint = defaultYes ? '[Y/n]' : '[y/N]';
  const ans = (await prompt(rl, `${question} ${hint} `)).trim().toLowerCase();
  return ans === '' ? defaultYes : ans === 'y' || ans === 'yes';
}

/** Create .myelin/ project dir, gitignore it, write project.yml */
function initMyelinDir(root, tools) {
  const dir = join(root, '.myelin');
  mkdirSync(dir, { recursive: true });

  // Write project.yml (track init state)
  const yml = `# Myelin project configuration
# Generated by: myelin init
project: ${root.split(/[\\/]/).pop()}
initialized: ${new Date().toISOString()}
tools:
${tools.map(t => `  ${t}: true`).join('\n')}
`;
  writeFileSync(join(dir, 'project.yml'), yml, 'utf8');

  // Gitignore .myelin/ (default: not committed — personal state)
  const gitignore = join(root, '.gitignore');
  const marker = '.myelin/';
  if (existsSync(gitignore)) {
    const content = readFileSync(gitignore, 'utf8');
    if (!content.includes(marker)) appendFileSync(gitignore, `\n# Myelin project state\n${marker}\n`);
  } else {
    writeFileSync(gitignore, `# Myelin project state\n${marker}\n`);
  }
}

/** Strip proxy env vars — model/language-server downloads can stall indefinitely
 *  behind our corporate-proxy chain (mitmproxy doesn't have every model-hub host
 *  in --ignore-hosts). Always sets (not just repairs) the CA-bundle env vars to
 *  our combined ~/.myelin/ca-bundle.pem: this corporate network does TLS
 *  interception at the network level (NetFree), independent of any app-level
 *  proxy setting, so *every* subprocess needs the corporate CA to verify
 *  outbound HTTPS — a shell that never sourced ~/.zshrc (e.g. a spawned
 *  non-interactive process) won't have these vars set at all, and a stale
 *  leftover ~/.tokenstack path is just as broken as having none. Tool
 *  indexing runs bypass the proxy and always use a valid cert path. */
function noProxyEnv() {
  const env = { ...process.env };
  delete env.HTTPS_PROXY; delete env.https_proxy;
  delete env.HTTP_PROXY;  delete env.http_proxy;
  const validCaBundle = join(homedir(), '.myelin', 'ca-bundle.pem');
  if (existsSync(validCaBundle)) {
    for (const v of ['SSL_CERT_FILE', 'REQUESTS_CA_BUNDLE', 'NODE_EXTRA_CA_CERTS', 'CURL_CA_BUNDLE', 'GIT_SSL_CAINFO', 'HEADROOM_CA_BUNDLE']) {
      env[v] = validCaBundle; // always set — never rely on the parent shell having it right
    }
  }
  return env;
}

/**
 * Run a command asynchronously with a hard timeout, streaming output prefixed
 * with a label. Using `spawn` (not `execSync`) is what makes real concurrency
 * possible — multiple tool runs across repos can be in flight at once instead
 * of blocking the Node event loop one at a time.
 *
 * `promptAnswerer(bufferedOutputSoFar)` — if provided, called on every output
 * chunk; return a string to write to stdin (and reset the buffer) or null/
 * undefined to keep waiting for more output. Used to answer serena's
 * per-language prompts contextually instead of blindly accepting/declining.
 */
function spawnAsync(command, args, { cwd, env, input, timeout, prefix, promptAnswerer } = {}) {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, { cwd, env: env ?? process.env, stdio: ['pipe', 'pipe', 'pipe'] });
    let buf = '';

    const emit = (data) => {
      const text = data.toString();
      for (const line of text.split('\n')) {
        if (line.trim()) console.log(`      [${prefix}] ${line}`);
      }
      if (promptAnswerer) {
        buf += text;
        const answer = promptAnswerer(buf);
        if (answer != null) { child.stdin.write(answer); buf = ''; }
      }
    };
    child.stdout.on('data', emit);
    child.stderr.on('data', emit);

    if (input) child.stdin.write(input);
    if (!promptAnswerer) child.stdin.end();

    let timedOut = false;
    const timer = timeout ? setTimeout(() => { timedOut = true; child.kill('SIGTERM'); }, timeout) : null;

    child.on('error', (err) => { clearTimeout(timer); reject(err); });
    child.on('close', (code, signal) => {
      clearTimeout(timer);
      if (timedOut) { const e = new Error(`timed out after ${timeout}ms`); e.timedOut = true; return reject(e); }
      if (signal)   { const e = new Error(`killed by ${signal}`); e.signal = signal; return reject(e); }
      if (code !== 0) { const e = new Error(`exited with code ${code}`); e.code = code; return reject(e); }
      resolve();
    });
  });
}

// serena always auto-enables the single dominant language without asking;
// "Enable X?" prompts are only for SECONDARY languages, and serena's own
// default when declined/blank is "No". These are Node/npm-based frontend
// companion language servers — same ecosystem as typescript, so they install
// the same way and don't need extra system-level deps (gems, native binary
// downloads, etc). Anything NOT in this set (bash, ruby, python, go, java...)
// is usually one or two incidental script/tooling files, not the repo's real
// language, and its language server is exactly what tends to fail (missing
// system deps, gem permissions, corporate CA not in that tool's own trust
// store) and abort the *entire* index for no real navigation benefit.
const SERENA_SAFE_COMPANION_LANGUAGES = new Set(['vue', 'svelte', 'javascript', 'typescript']);

function serenaPromptAnswerer(buf) {
  const m = buf.match(/Enable (\S+) \([\d.]+% of source files\)\?\s*\[y\/N\]\s*$/);
  if (!m) return null;
  return SERENA_SAFE_COMPANION_LANGUAGES.has(m[1].toLowerCase()) ? 'y\n' : 'n\n';
}

const TOOLS = [
  {
    id: 'serena',
    label: 'Serena (LSP code index — symbol-precise navigation)',
    check: (root) => existsSync(join(root, '.serena', 'project.yml')) || existsSync(join(root, '.myelin', 'project.yml')),
    // Synchronous path — used only in interactive mode where `stdio: inherit`
    // lets the user answer serena's own per-language prompts directly.
    run: (root) => {
      const alreadyRegistered = existsSync(join(root, '.serena', 'project.yml'));
      const cmd = alreadyRegistered ? `serena project index "${root}"` : `serena project create --index "${root}"`;
      execSync(cmd, { env: noProxyEnv(), timeout: 240_000, stdio: 'inherit' });
    },
    // Async path — used for non-interactive concurrent (recursive --yes) runs.
    // Answers each "Enable <language>?" prompt contextually (see
    // SERENA_SAFE_COMPANION_LANGUAGES above) instead of blindly accepting or
    // declining every one.
    runAsync: (root, prefix) => {
      const alreadyRegistered = existsSync(join(root, '.serena', 'project.yml'));
      const args = alreadyRegistered ? ['project', 'index', root] : ['project', 'create', '--index', root];
      return spawnAsync('serena', args, { env: noProxyEnv(), timeout: 240_000, prefix, promptAnswerer: serenaPromptAnswerer });
    },
  },
  {
    id: 'semble',
    label: 'Semble (semantic code search index)',
    check: (_root) => false,
    // NOTE: `semble --content code` (no subcommand) launches semble's MCP
    // *server* mode (see semble/cli.py: any first arg not in the known
    // subcommand set falls through to `_mcp_main()`), which blocks forever
    // waiting for JSON-RPC on stdin. There is no dedicated `semble index`
    // subcommand — building the index is a documented side effect of running
    // a throwaway `search` query, which is what we do here instead.
    run: (root, _yes) => {
      execSync(`semble search "codebase overview" "${root}" --content code`, {
        cwd: root, env: noProxyEnv(), stdio: ['ignore', 'ignore', 'inherit'], timeout: 300_000,
      });
    },
    runAsync: (root, prefix) => spawnAsync(
      'semble', ['search', 'codebase overview', root, '--content', 'code'],
      { env: noProxyEnv(), timeout: 300_000, prefix }
    ),
  },
];

async function initRepoInteractive(root, rl, enabledTools) {
  const name = root.split(/[\\/]/).pop();
  console.log(`\n   📁 ${name}  (${root})`);
  const results = [];
  for (const tool of TOOLS.filter(t => enabledTools.includes(t.id))) {
    const alreadyDone = tool.check(root);
    const labelSuffix = alreadyDone ? ' (already done — re-run?)' : '';
    const run = await confirm(rl, `      Run ${tool.id}${labelSuffix}?`, !alreadyDone);
    if (run) {
      // readline puts a TTY stdin into raw mode (no echo/canonical line
      // buffering) to support keypress events. That raw-mode state leaks into
      // any child process we spawn with stdio 'inherit'/'pipe' below, which
      // breaks tools (e.g. serena) doing blocking canonical reads via
      // input() — the terminal looks completely unresponsive. Restore
      // cooked mode for the duration of the child process call.
      const wasRaw = Boolean(process.stdin.isTTY && process.stdin.isRaw);
      if (wasRaw) process.stdin.setRawMode(false);
      try {
        tool.run(root);
        console.log(`      ✓ ${tool.id}`);
        results.push({ id: tool.id, ok: true });
      } catch (e) {
        const timedOut = e.timedOut || e.signal === 'SIGTERM';
        console.warn(`      ⚠ ${tool.id} ${timedOut ? 'timed out — skipped' : `failed: ${e.message.split('\n')[0]}`}`);
        results.push({ id: tool.id, ok: false });
      } finally {
        if (wasRaw) process.stdin.setRawMode(true);
      }
    } else {
      console.log(`      · ${tool.id} skipped`);
      results.push({ id: tool.id, ok: false });
    }
  }
  finishRepo(root, results);
  return results;
}

/** Non-interactive: run every enabled tool for this repo concurrently — one
 *  hung/slow tool must never delay the others (in-repo or cross-repo). */
async function initRepoConcurrent(root, enabledTools) {
  const name = root.split(/[\\/]/).pop();
  console.log(`\n   📁 ${name}  (${root}) — running tools concurrently`);
  const tools = TOOLS.filter(t => enabledTools.includes(t.id));
  const settled = await Promise.allSettled(tools.map(async (tool) => {
    const prefix = `${name}/${tool.id}`;
    try {
      await tool.runAsync(root, prefix);
      console.log(`      ✓ ${prefix}`);
      return { id: tool.id, ok: true };
    } catch (e) {
      const timedOut = e.timedOut || e.signal === 'SIGTERM';
      console.warn(`      ⚠ ${prefix} ${timedOut ? 'timed out — skipped' : `failed: ${e.message.split('\n')[0]}`}`);
      return { id: tool.id, ok: false };
    }
  }));
  const results = settled.map(s => s.value ?? { id: '?', ok: false });
  finishRepo(root, results);
  return results;
}

/** Copilot CLI hook config content — see src/hooks/copilot-serena-guard.mjs
 * for why this bridges through `myelin serena-guard` instead of calling
 * `serena-hooks` directly (schema mismatch between Serena's Claude/VSCode
 * output envelope and Copilot CLI's flat decision schema). Mirrors the
 * PascalCase/matcher structure Serena's own docs use for their "VSCode"
 * hooks file, which Serena explicitly documents as also being the file to
 * reuse for Copilot CLI. */
export function copilotSerenaHooksConfig() {
  const hook = (event) => ({
    matcher: '',
    hooks: [{ type: 'command', command: `myelin serena-guard --event=${event}`, timeoutSec: 10 }],
  });
  return JSON.stringify({
    version: 1,
    hooks: {
      PreToolUse: [hook('preToolUse')],
      SessionStart: [hook('sessionStart')],
      Stop: [hook('stop')],
    },
  }, null, 2) + '\n';
}

/** Wire the Copilot CLI <-> Serena hook bridge at project level, but ONLY
 * for repos where Serena has actually been set up (`.serena/project.yml`
 * present) — nudging toward tools that were never configured for this repo
 * would be worse than doing nothing. Written to `.github/hooks/`, the
 * documented per-repo hook location for Copilot CLI. Not gitignored
 * globally like `.myelin/`, because this specific file is deliberately
 * excluded from commits below: the `myelin` command it invokes only
 * resolves on machines that have Myelin installed, and Copilot CLI's
 * preToolUse hooks are fail-CLOSED on a missing-command spawn error — for a
 * teammate without Myelin, a committed copy of this file would silently
 * deny every single tool call. It must stay personal, uncommitted state. */
export function writeCopilotSerenaHooks(root) {
  if (!existsSync(join(root, '.serena', 'project.yml'))) return;

  const hooksDir = join(root, '.github', 'hooks');
  mkdirSync(hooksDir, { recursive: true });
  writeFileSync(join(hooksDir, 'copilot-serena-guard.json'), copilotSerenaHooksConfig(), 'utf8');

  const gitignore = join(root, '.gitignore');
  const marker = '.github/hooks/copilot-serena-guard.json';
  if (existsSync(gitignore)) {
    const content = readFileSync(gitignore, 'utf8');
    if (!content.includes(marker)) appendFileSync(gitignore, `\n# Myelin: machine-specific Copilot CLI hook (requires Myelin installed)\n${marker}\n`);
  } else {
    writeFileSync(gitignore, `# Myelin: machine-specific Copilot CLI hook (requires Myelin installed)\n${marker}\n`);
  }
}

function finishRepo(root, results) {
  // Never let a failure here (e.g. permissions) abort the whole recursive run
  try {
    initMyelinDir(root, results.filter(r => r.ok).map(r => r.id));
  } catch (e) {
    console.warn(`      ⚠ could not write .myelin/project.yml: ${e.message.split('\n')[0]}`);
  }
  try {
    writeAgentsInstructions(root);
  } catch (e) {
    console.warn(`      ⚠ could not write AGENTS.md: ${e.message.split('\n')[0]}`);
  }
  try {
    writeCopilotSerenaHooks(root);
  } catch (e) {
    console.warn(`      ⚠ could not write Copilot Serena hook config: ${e.message.split('\n')[0]}`);
  }
}

/** Repo-level instruction file (Copilot CLI, and other AGENTS.md-aware
 *  agents, read this at the repo root). This is the "repo" scope
 *  counterpart to install.mjs's global ~/.claude/CLAUDE.md write — see
 *  src/config/instruction-snippets.mjs for the shared snippet registry and
 *  scope/provider/model rules. */
function writeAgentsInstructions(root) {
  const cfg = _loadConfigSync();
  const block = renderManagedBlock({ target: 'repo', provider: 'copilot', model: cfg.copilot?.model, cfg });
  if (!block) return;
  writeManagedSection(join(root, 'AGENTS.md'), `\n${block}`);
}

let _cachedCfg = null;
function _loadConfigSync() {
  // init.mjs's callers are synchronous (finishRepo runs inside both the
  // interactive and concurrent per-repo paths); config.yaml is small and
  // rarely present at this stage, so a plain sync read/parse keeps this
  // dependency-free rather than threading an async loadConfig() through.
  if (_cachedCfg) return _cachedCfg;
  const configPath = join(homedir(), '.myelin', 'config.yaml');
  let userConfig = {};
  if (existsSync(configPath)) {
    try { userConfig = parseYaml(readFileSync(configPath, 'utf8')) ?? {}; }
    catch { /* fall back to defaults */ }
  }
  _cachedCfg = mergeDeep(DEFAULT_CONFIG, userConfig);
  return _cachedCfg;
}

/** Run `fn` over `items` with at most `limit` in flight concurrently. */
async function mapLimit(items, limit, fn) {
  const ret = new Array(items.length);
  let i = 0;
  async function worker() {
    while (i < items.length) {
      const idx = i++;
      ret[idx] = await fn(items[idx], idx);
    }
  }
  await Promise.all(Array.from({ length: Math.min(limit, items.length) }, worker));
  return ret;
}

export async function runInit({ yes = false, recursive = false, dir = process.cwd(), depth = 4 } = {}) {
  let rl;

  // Collect repos to init
  let repos = [];
  if (recursive) {
    repos = findGitRepos(dir, depth);
    if (repos.length === 0) {
      console.log(`\n⚠  No git repositories found under ${dir}\n`); return false;
    }
    console.log(`\n🧬 Myelin Init (recursive) — found ${repos.length} repo(s) under ${dir}`);
    repos.forEach((r, i) => console.log(`   ${i + 1}. ${r.replace(dir, '.')}`));
  } else {
    const root = findGitRoot(dir);
    if (!root) { console.log(`\n⚠  Not inside a git repository (cwd: ${dir})\n`); return false; }
    repos = [root];
    console.log(`\n🧬 Myelin Init — ${root.split(/[\\/]/).pop()}  (${root})`);
  }

  if (!yes) {
    rl = createInterface({ input: process.stdin, output: process.stdout });
    const proceed = await confirm(rl, `\n   Initialize ${repos.length} repo(s)?`);
    if (!proceed) { rl.close(); console.log('   Cancelled.\n'); return false; }
  }

  // Choose tools (once, applies to all repos)
  let enabledTools = TOOLS.map(t => t.id);
  if (!yes && rl) {
    console.log('\n   Select tools to run:');
    enabledTools = [];
    for (const tool of TOOLS) {
      const run = await confirm(rl, `     ${tool.label}?`);
      if (run) enabledTools.push(tool.id);
    }
  }

  let total = 0, ok = 0, reposFailed = 0;
  const trackResults = (results) => { total += results.length; ok += results.filter(r => r.ok).length; };

  if (yes) {
    // Non-interactive: tools within a repo run concurrently, and repos run
    // concurrently across a capped pool — nothing can delay anything else.
    // Cap kept modest (not repos.length) because each repo already runs
    // multiple tools concurrently, and serena itself spawns 2-3 LSP
    // subprocesses per repo — too many repos at once causes resource
    // contention (CPU/memory) that manifests as spurious language-server
    // startup failures, even though each repo indexes fine in isolation.
    const CONCURRENCY = 2;
    await mapLimit(repos, CONCURRENCY, async (root) => {
      try {
        trackResults(await initRepoConcurrent(root, enabledTools));
      } catch (e) {
        reposFailed++;
        console.warn(`      ⚠ ${root} failed unexpectedly: ${e.message.split('\n')[0]} — continuing`);
      }
    });
  } else {
    // Interactive: prompts are inherently sequential (single user, one terminal)
    for (const root of repos) {
      try {
        trackResults(await initRepoInteractive(root, rl, enabledTools));
      } catch (e) {
        reposFailed++;
        console.warn(`      ⚠ ${root} failed unexpectedly: ${e.message.split('\n')[0]} — continuing to next repo`);
      }
    }
  }

  if (rl) rl.close();
  console.log(`\n   ✓ Init complete — ${ok}/${total} operations succeeded across ${repos.length} repo(s)${reposFailed ? ` (${reposFailed} repo(s) hit unexpected errors)` : ''}.\n`);
  return true;
}
