import { existsSync, readFileSync, writeFileSync } from 'node:fs';

/**
 * Fail-open hardening for Copilot CLI preToolUse hooks.
 *
 * preToolUse is the ONE Copilot hook event that is fail-CLOSED on a crash or
 * non-zero exit (docs.github.com/en/copilot/reference/hooks-reference) — a hook
 * that errors denies the tool call with "Denied by preToolUse hook (hook
 * errored)". Any hook whose command runs an external binary (rtk, a python
 * bridge, `myelin` itself) therefore risks bricking every tool call the moment
 * that binary isn't resolvable or crashes. These helpers append a bash suffix
 * that forces the hook to exit 0 (fail-open) on any failure while still
 * honouring an intentional exit-2 "deny" from the underlying command.
 */

// Doubles as the idempotency guard: if a command already contains this token it
// has already been hardened, so we never wrap it twice.
export const FAIL_OPEN_MARKER = '__myelin_failopen';

/** Wrap a bash command string so it can never fail-CLOSE a tool call. With
 *  preserveDeny (default) an intentional exit 2 is passed through as a deny and
 *  every other non-zero/crash becomes exit 0; without it, always exit 0. */
export function makeFailOpen(cmd, { preserveDeny = true } = {}) {
  if (typeof cmd !== 'string' || !cmd.trim()) return cmd;
  if (cmd.includes(FAIL_OPEN_MARKER)) return cmd;
  const base = cmd.trimEnd().replace(/;\s*$/, '');
  const guard = preserveDeny
    ? `${FAIL_OPEN_MARKER}=$?; [ "$${FAIL_OPEN_MARKER}" = 2 ] && exit 2; exit 0`
    : `${FAIL_OPEN_MARKER}=0; exit 0`;
  return `${base}; ${guard}`;
}

const defaultFs = { existsSync, readFileSync, writeFileSync };

/**
 * Post-process an already-written Copilot hook JSON file so the given events'
 * commands are fail-open. Used for hooks generated by external tools we don't
 * control (e.g. token-optimizer). Only the listed shell fields are touched
 * (the fail-open suffix is bash syntax, so `powershell`/`command` are left
 * alone by default). Defensive + idempotent; never throws.
 */
export function hardenCopilotHookFile({
  path,
  events = ['preToolUse', 'PreToolUse'],
  fields = ['bash'],
  preserveDeny = true,
  fs = defaultFs,
} = {}) {
  try {
    if (!fs.existsSync(path)) return { action: 'absent', path };
    let config;
    try { config = JSON.parse(fs.readFileSync(path, 'utf8')); } catch { return { action: 'unparseable', path }; }
    let changed = false;
    const harden = (obj) => {
      if (!obj || typeof obj !== 'object') return;
      for (const field of fields) {
        if (typeof obj[field] === 'string') {
          const next = makeFailOpen(obj[field], { preserveDeny });
          if (next !== obj[field]) { obj[field] = next; changed = true; }
        }
      }
    };
    for (const ev of events) {
      const entries = config?.hooks?.[ev];
      if (!Array.isArray(entries)) continue;
      for (const entry of entries) {
        harden(entry);
        if (Array.isArray(entry?.hooks)) for (const h of entry.hooks) harden(h);
      }
    }
    if (changed) fs.writeFileSync(path, `${JSON.stringify(config, null, 2)}\n`, 'utf8');
    return { action: changed ? 'hardened' : 'already-safe', path };
  } catch {
    return { action: 'error', path };
  }
}
